spring.application.name=smartmetrix-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/smartmetrix
spring.datasource.username=postgres
spring.datasource.password=Rajnish@9219

spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=smartmetrix-local-jwt-secret-2026-secure
app.jwt.expiration=3600000

app.cors.allowed-origins=http://localhost:5173,http://localhost:5174

logging.level.org.springframework.security=INFO