spring.application.name=smartmetrix-backend

# ==============================
# DATABASE
# ==============================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# ==============================
# JWT
# ==============================
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=3600000

# ==============================
# CORS
# ==============================
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# ==============================
# CERTIFICATE QR VERIFICATION
# ==============================
app.verification.base-url=${APP_VERIFICATION_BASE_URL}

# ==============================
# LOGGING
# ==============================
logging.level.org.springframework.security=INFO